### ISSUE TITLE
dont know where to put the dll and .md file with melon

### ISSUE THREAD

**Issue by ddukle** [ObscureGreenTea/ForceCloneFixed#1]
please help im new with vrchat mods and idk where to put the dll and .md

**Comment by ObscureGreenTea** [comment]
Have you ran the melon loader **installer**?

Did you point it to your **VRChat.exe**?

If so, in the games directory _(Should be something like **C:/Program Files (x86)/Steam/steamapps/common/VRChat/**)_ you should see a folder named MelonLoader _(if you did it correctly)_, next to it you should see a folder named **mods**. If you don't then make sure you run the game **atleast once** after installing melon loader. If you still don't see a folder named **mods** then you want to create one with that name. Once you've done that, put the **ForceCloneFixed.dll** in that folder. The **.md** file is **USELESS** and wont be needed.

After this, when opening the game you should see a console window pop up, somewhere in there you should see something saying this
![Force Clone v1.1 by ObscureGreenTea / Huntereb](https://i.imgur.com/tpm8ifO.png)

When clicking on a user you should see this button appear
![Yoink thy style](https://i.imgur.com/u4FLSI7.png)


If you need more help, Feel free to ask.

**Comment by ObscureGreenTea** [comment]
Closing, Assuming its working for you now.
