### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by wolfboy5206** [ObscureGreenTea/ForceCloneFixed#4]
why have error code
not working

**Comment by InactiveCoyote** [comment]
this show up as error [ERROR] System.MissingMethodException: void UiTooltip.set_text(string)
  at MelonLoader.MelonHandler.OnSceneWasLoaded (System.Int32 buildIndex, System.String sceneName) [0x00028] in <61bd2bb7fbe24a28bc977e05ef482f41>:0

**Comment by SenTakS** [comment]
I think the owner gave up on us

**Comment by wolfboy5206** [comment]
fuck off

**Comment by SenTakS** [comment]
? I am just saying there has been no patch in long time, why mad? :(

**Comment by wolfboy5206** [comment]
I misunderstood
so sorry

**Comment by ObscureGreenTea** [comment]
Fixed, Refer to issue #3
